[workspace]
members = [
  "lib",
  "bin",
  "rocksdb",
]
resolver = "2"

[workspace.metadata]
name = "flakebox-tutorial"
version = "0.1.0"
edition = "2021"

[workspace.package]
edition = "2021"

[profile.ci]
debug = "line-tables-only"
inherits = "dev"
incremental = false
lto = "off"
